### ISSUE TITLE
Polymorphism

### ISSUE THREAD

**Issue by imtrobin** [netheril96/StaticJSON#23]
Hi ,I noticed I get object sliced if I using a list shared_ptr to store base class pointer. Is there a way to support polymorphism properly?

**Comment by netheril96** [comment]
Could you post a minimum conpilable example to demonstrate your issue? I don't understand it just from your description.

**Comment by imtrobin** [comment]
class Base;
class Dervied : public Base:

list < shared_ptr <Base> >  baseList;

baseList.pushback (new Derived ());

When I serialize baseList, it access as as Based instead of Derived. Similarily, if I want to deserialize a list of Derived objects into list <shared_ptr <Base>>, it doesn't work.

**Comment by imtrobin** [comment]
do u need an full example that compiles?

**Comment by netheril96** [comment]
OK, I got the problem. Serialization should work if the `staticjson_init` method is virtual and overridden in the subclass. If not, please post an example for me to test.

Deserialization with subclasses won't be supported. That requires a complicated mechanism since C++ has no reflection. In addition, deserializing into arbitrary classes has been a source of vulnerabilities in many languages (Java, Python, etc). It is a bad idea in my opinion. It is better to deserialize into a fixed layout struct, and then convert to the appropriate subclasses manually.

**Comment by imtrobin** [comment]
Ok. the serialization works.

Ok about deserialization
