### ISSUE TITLE
support for std::array

### ISSUE THREAD

**Issue by ng5** [netheril96/StaticJSON#26]
Please can you confirm if it is possible to add support for std::array. it should have same semantics to iterator the list. (e.g. std::vector, std::list etc)

**Comment by netheril96** [comment]
Yes. The original version has it, and the current version still has the `ArrayLengthMismatchError`. I removed it during rewrite because I thought no one actually had the need for it. I will add it back after my three month internship ends (in case of copyright issues).

My original design mandates that the JSON array has length N for a element declared in C++ as `std::array<T, N>`, or else an `ArrayLengthMismatchError` will be returned. Do you think that is what you need? Or a more lax parsing?

**Comment by ng5** [comment]
thank you so much for coming back. Yes, std::array<T,N> is exactly what i need. For now I'm using std::tuple because it is supported in your library. But ofcourse it is not a substitute for std::array.

**Comment by netheril96** [comment]
Support added in 02f0f22

**Comment by ng5** [comment]
thank you, much obliged.
